### ISSUE TITLE
Update License information in package.json

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#11]
We use Apache License 2.

**Comment by hoang-dao** [comment]
resolved by https://github.com/lecle/aloxide/pull/39, @flowersinthesand please help closing this.

**Comment by flowersinthesand** [comment]
@hoang-dao confirmed it's resolved by https://github.com/lecle/aloxide/commit/120e0edad9077ece50aedbe18789392aefb3e6ef 😄
