### ISSUE TITLE
As a user I want to use a well-made SDK so that I don't need to reinvent the wheel

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#27]
## Acceptance Criteria

- [ ] JavaScript
- [ ] Android
- [ ] iOS
- [ ] Python

**Comment by tiendq** [comment]
Python is here https://github.com/lecle/aloxide-sdk-python

**Comment by flowersinthesand** [comment]
@tiendq Great. Thanks for your contribution!
