### ISSUE TITLE
There are 2 demux versions being used

### ISSUE THREAD

**Issue by tiendq** [lecle/aloxide#58]
`v4.0.0` official and the latest `v5.0.2-581` of `demux` are used in packages, their API is slightly different and not compatible. It might cause issues with `demux-eos`.

Expectation: should pick one version to use consistently in all packages.

**Comment by tiendq** [comment]
@manh-vv it seems you fixed this issue (using the same version of Demux)?

**Comment by manh-vv** [comment]
Right, I fixed the problem.
