### ISSUE TITLE
modules/components in aloxide

### ISSUE THREAD

**Issue by manh-vv** [lecle/aloxide#6]
list out modules/components in aloxide

**Comment by manh-vv** [comment]
This is an ongoing list. We can update our document base on this list.

/cc @quocle108 @flowersinthesand 

|  moduels | description |
| --- | --- |
|  @aloxide/abstraction | provide tool for generating smart-contract |
|  @aloxide/bridge | provide adapter for integrating with blockchain |
|  @aloxide/api-gateway | provide an API template for the back-end side |
|  @aloxide/sdk | TBD |
|  @aloxide/demux | TBD |

**Comment by flowersinthesand** [comment]
What's the role of `@aloxide/demux`?

**Comment by manh-vv** [comment]
> What's the role of `@aloxide/demux`?

It is a package helping api-gateway up to date with blockchain. I am not sure yet :).

**Comment by manh-vv** [comment]
I will close this issue, and refer to it later when we need to update some wikis.
