### ISSUE TITLE
Refactor Contract Generator and Bridge to be cleaner and simpler

### ISSUE THREAD

**Issue by hoang-dao** [lecle/aloxide#62]
Refactor Contract Generator and Bridge to be cleaner and simpler:
- [x] Bring logic of Multi Adapters to Contract Generator to make it simpler and more correct.
- [x] Move Entities validation logic from Contract Generator to Schema Validator.
- [ ] Move Sequelize/Model Adapter to example of customized Adapter based on our current [High Level Architecture](https://github.com/lecle/aloxide/wiki/High-level-Architecture).

**Comment by hoang-dao** [comment]
@manh-vv what do you think? Can you help me check the PR? Thanks.

**Comment by manh-vv** [comment]
@hoang-dao please update MR to have these update:

- [x] Bring logic of Multi Adapters to Contract Generator to make it simpler and more correct.
- [x] Move Entities validation logic from Contract Generator to Schema Validator.

**Comment by hoang-dao** [comment]
As discussed, current [High Level Architecture](https://github.com/lecle/aloxide/wiki/High-level-Architecture) should be updated, we should support more template other than current blockchain smart contracts (ICON, EOS, CAN), for example: sequelize model
